### ISSUE TITLE
WatchTree replying all events if the tree has some history.

### ISSUE THREAD

**Issue by mthenw** [abronan/libkv#22]
One more thing around `WatchTree` in etcd v3 :)

Right now, if there are no subkeys under some key, but there were in the past, `Watch` with `WithRev` will return all events that happened in the past. It happens because List return no key/value pairs and the rev number is set to 1. 

I guess it's not intended behavior. In case of empty List result, we should start with the current rev number. Does it make sense?

**Comment by abronan** [comment]
Oh! nice find :)

I feel like just removing the initial `List` call from all `Watch/WatchTree` calls would make the most sense, but we need to align all Key/Value stores and this might break a few usage scenarios. It is costly to return the full list of keys under a prefix prior to the watch events, we might have thousands of keys under that prefix.

For now I guess we could just treat this as a special case: simply call `Watch` without the `WithRev` if List returns no keys. Does that sound right?

**Comment by mthenw** [comment]
> For now I guess we could just treat this as a special case: simply call Watch without the WithRev if List returns no keys. Does that sound right?

Oh, yeah, make sense. I will submit a PR later today :)

**Comment by mthenw** [comment]
Actually, the best solution would be to get rev not from the oldest KV pair but from the moment when `List` response was returned. This value is accessible but not on the level of `WatchTree`. It's [here](https://github.com/abronan/libkv/blob/master/store/etcd/v3/etcd.go#L383) in `resp` object.

**Comment by abronan** [comment]
You mean the `Header.Revision` in the `Resp`? I bet that could work but I cannot test now.

We can refactor the `List` call by creating a private/internal `list` function that returns the `Header.Revision` along with the list of keys and the error. Then the normal `List` call would use that internal `list` but ignore the header revision. We can then use this internal `list` in the `WatchTree` call to get that piece of information and feed it to `WithRev`.

**Comment by mthenw** [comment]
This is **exactly** what I'm doing right now :)
